**IMPORT NECESSERY LIBERY**

In [1]:
import numpy as np
import pandas as pd

**IMPORT CSV FILE**

In [2]:
data=pd.read_csv('/content/MOCK_DATA (1).csv')

**OBSEVE THE DATASET**

In [3]:
pd.DataFrame(data)

,booking_id,customer_id,provider_id,booking_date,service_type,status,quoted_price,final_price,duration_minutes,zip_code,customer_rating
0,1,1,1,3/22/2026,lawn mowing,pending,401.88,199.81,108.0,NaN,2
1,2,2,2,3/6/2026,hedge trimming,completed,419.45,183.91,58.0,NaN,5
2,3,3,3,6/6/2026,weed control,pending,318.93,114.12,200.0,NaN,1
3,4,4,4,11/11/2025,lawn mowing,completed,385.02,NaN,152.0,NaN,4
4,5,5,5,4/11/2026,hedge trimming,completed,249.24,177.54,57.0,NaN,4
...,...,...,...,...,...,...,...,...,...,...,...
995,996,996,996,1/6/2026,weed control,pending,162.70,24.29,96.0,92640,1
996,997,997,997,10/26/2025,lawn mowing,confirmed,NaN,155.29,240.0,NaN,5
997,998,998,998,12/5/2025,weed control,pending,140.93,73.06,70.0,88930,4
998,999,999,999,5/30/2026,lawn mowing,completed,282.01,39.35,232.0,36900-000,1
999,1000,1000,1000,10/24/2025,hedge trimming,pending,NaN,230.15,150.0,8208,4

In [13]:
print(data.info)

<bound method DataFrame.info of      booking_id  customer_id  provider_id booking_date    service_type  \
0             1            1            1    3/22/2026     lawn mowing
1             2            2            2     3/6/2026  hedge trimming
2             3            3            3     6/6/2026    weed control
3             4            4            4   11/11/2025     lawn mowing
4             5            5            5    4/11/2026  hedge trimming
..          ...          ...          ...          ...             ...
995         996          996          996     1/6/2026    weed control
996         997          997          997   10/26/2025     lawn mowing
997         998          998          998    12/5/2025    weed control
998         999          999          999    5/30/2026     lawn mowing
999        1000         1000         1000   10/24/2025  hedge trimming

        status  quoted_price  final_price  duration_minutes   zip_code  \
0      pending        401.88       199.81             108.0        NaN
1    completed        419.45       183.91              58.0        NaN
2      pending        318.93       114.12             200.0        NaN
3    completed        385.02          NaN             152.0        NaN
4    completed        249.24       177.54              57.0        NaN
..         ...           ...          ...               ...        ...
995    pending        162.70        24.29              96.0      92640
996  confirmed           NaN       155.29             240.0        NaN
997    pending        140.93        73.06              70.0      88930
998  completed        282.01        39.35             232.0  36900-000
999    pending           NaN       230.15             150.0       8208

     customer_rating
0                  2
1                  5
2                  1
3                  4
4                  4
..               ...
995                1
996                5
997                4
998                1
999                4

[1000 rows x 11 columns]>

**OBSERVE AND OPTIMISE FOR TECNICAL AND ANALYSIS TEAM**

In [8]:
data['booking_date'].isna().sum()

np.int64(0)

In [14]:
data1=data['booking_id']

In [17]:
data1.drop_duplicates().isnull().sum()

np.int64(0)

In [19]:
data['customer_rating'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 1000 entries, 0 to 999
Series name: customer_rating
Non-Null Count  Dtype
--------------  -----
1000 non-null   int64
dtypes: int64(1)
memory usage: 7.9 KB

In [21]:
print(data['customer_rating'].head(5))

0    2
1    5
2    1
3    4
4    4
Name: customer_rating, dtype: int64

In [23]:
data['customer_id'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 1000 entries, 0 to 999
Series name: customer_id
Non-Null Count  Dtype
--------------  -----
1000 non-null   int64
dtypes: int64(1)
memory usage: 7.9 KB

In [24]:
print(data['customer_id'].head(5))

0    1
1    2
2    3
3    4
4    5
Name: customer_id, dtype: int64

In [53]:
data['customer_rating'].mean()

np.float64(2.983)

In [55]:
data.groupby('customer_rating')['customer_rating'].count()

customer_rating
1    200
2    197
3    207
4    212
5    184
Name: customer_rating, dtype: int64

In [26]:
data['duration_minutes'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 1000 entries, 0 to 999
Series name: duration_minutes
Non-Null Count  Dtype
--------------  -----
952 non-null    float64
dtypes: float64(1)
memory usage: 7.9 KB

In [28]:
print(data['duration_minutes'].head(3))

0    108.0
1     58.0
2    200.0
Name: duration_minutes, dtype: float64

In [27]:
data['duration_minutes'].isnull().sum()

np.int64(48)

In [29]:
data['duration_minutes'].fillna(0)

0      108.0
1       58.0
2      200.0
3      152.0
4       57.0
       ...
995     96.0
996    240.0
997     70.0
998    232.0
999    150.0
Name: duration_minutes, Length: 1000, dtype: float64

In [51]:
data['duration_minutes'].max()

240.0

In [52]:
data['duration_minutes'].mean()

np.float64(128.0609243697479)

In [31]:
data['final_price'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 1000 entries, 0 to 999
Series name: final_price
Non-Null Count  Dtype
--------------  -----
927 non-null    float64
dtypes: float64(1)
memory usage: 7.9 KB

In [32]:
data['final_price'].isnull().sum()

np.int64(73)

In [33]:
data['final_price'].fillna(0)

0      199.81
1      183.91
2      114.12
3        0.00
4      177.54
        ...
995     24.29
996    155.29
997     73.06
998     39.35
999    230.15
Name: final_price, Length: 1000, dtype: float64

In [48]:
data['final_price'].max()

499.35

In [50]:
data['final_price'].mean()

np.float64(254.46759439050703)

In [34]:
data['provider_id'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 1000 entries, 0 to 999
Series name: provider_id
Non-Null Count  Dtype
--------------  -----
1000 non-null   int64
dtypes: int64(1)
memory usage: 7.9 KB

In [35]:
data['quoted_price'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 1000 entries, 0 to 999
Series name: quoted_price
Non-Null Count  Dtype
--------------  -----
958 non-null    float64
dtypes: float64(1)
memory usage: 7.9 KB

In [37]:
data['quoted_price'].fillna(0)

0      401.88
1      419.45
2      318.93
3      385.02
4      249.24
        ...
995    162.70
996      0.00
997    140.93
998    282.01
999      0.00
Name: quoted_price, Length: 1000, dtype: float64

In [38]:
data['service_type'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 1000 entries, 0 to 999
Series name: service_type
Non-Null Count  Dtype
--------------  -----
1000 non-null   object
dtypes: object(1)
memory usage: 7.9+ KB

In [39]:
data['service_type'].head(3)

0       lawn mowing
1    hedge trimming
2      weed control
Name: service_type, dtype: object

In [42]:
data.groupby('service_type')['service_type'].count()

service_type
hedge trimming    353
lawn mowing       345
weed control      302
Name: service_type, dtype: int64

In [43]:
data['status'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 1000 entries, 0 to 999
Series name: status
Non-Null Count  Dtype
--------------  -----
1000 non-null   object
dtypes: object(1)
memory usage: 7.9+ KB

In [47]:
data.groupby('status')['status'].count()

status
completed    333
confirmed    332
pending      335
Name: status, dtype: int64

In [57]:
data['zip_code'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 1000 entries, 0 to 999
Series name: zip_code
Non-Null Count  Dtype
--------------  -----
482 non-null    object
dtypes: object(1)
memory usage: 7.9+ KB

In [61]:
data['booking_date'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 1000 entries, 0 to 999
Series name: booking_date
Non-Null Count  Dtype
--------------  -----
1000 non-null   object
dtypes: object(1)
memory usage: 7.9+ KB

In [64]:
pd.to_datetime(data['booking_date'],format='mixed',errors='coerce').isnull().sum()

np.int64(0)

In [67]:
data['booking_date']=pd.to_datetime(data['booking_date'],format='mixed',errors='coerce')

In [82]:
data.groupby(data['booking_date'].dt.year)['booking_id'].count()

booking_date
2025    248
2026    752
Name: booking_id, dtype: int64

In [83]:
data['booking_id'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 1000 entries, 0 to 999
Series name: booking_id
Non-Null Count  Dtype
--------------  -----
1000 non-null   int64
dtypes: int64(1)
memory usage: 7.9 KB

In [86]:
data['quoted_price'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 1000 entries, 0 to 999
Series name: quoted_price
Non-Null Count  Dtype
--------------  -----
958 non-null    float64
dtypes: float64(1)
memory usage: 7.9 KB

In [87]:
data['provider_id'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 1000 entries, 0 to 999
Series name: provider_id
Non-Null Count  Dtype
--------------  -----
1000 non-null   int64
dtypes: int64(1)
memory usage: 7.9 KB

In [88]:
data.groupby("provider_id")['provider_id'].count()

provider_id
1       1
2       1
3       1
4       1
5       1
       ..
996     1
997     1
998     1
999     1
1000    1
Name: provider_id, Length: 1000, dtype: int64

**EXTRACT THE OPTIMISED DATASET**

In [89]:
data.to_excel('Lawn_org_analysis.xlsx')